version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: team_sync
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
